export enum EEnvVariables {
    PORT = 'PORT',
    CLIENT_URL = 'CLIENT_URL',
    MONGO_URL = 'MONGO_URL',
    MONGO_DB_NAME = 'MONGO_DB_NAME',
    ACCESS_SECRET = 'ACCESS_SECRET',
    REFRESH_SECRET = 'REFRESH_SECRET',
}